name: Fast Config Collector

on:
  schedule:
    - cron: '*/10 * * * *' # اجرا هر ۱۰ دقیقه
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3 # اگر بیشتر از ۳ دقیقه شد قطعش کن (صرفه‌جویی)
    permissions:
      contents: write

    steps:
      - name: Checkout (Lightweight)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1 # دانلود سریع فقط آخرین نسخه

      - name: Run Optimized Script
        run: python collector.py

      - name: Push Changes
        run: |
          git config --global user.name "Actions Bot"
          git config --global user.email "bot@github.com"
          git add configs/proxy_configs.txt
          # اگر تغییری نبود ارور نده و خارج شو
          git diff --quiet && git diff --staged --quiet || (git commit -m "Up" && git push)
